# Generated by Django 2.0.4 on 2018-04-16 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('playcount', models.CharField(max_length=12, verbose_name='Прослушиваний')),
                ('image_url', models.CharField(max_length=255, verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
                ('playcount', models.CharField(max_length=12, verbose_name='Прослушиваний')),
                ('listeners', models.CharField(max_length=12, verbose_name='Слушателей')),
                ('image_url', models.CharField(max_length=255, verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тэг')),
                ('color', models.CharField(max_length=10, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('duration', models.PositiveIntegerField(max_length=12, verbose_name='Продолжительность (s)')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Artist')),
                ('tags', models.ManyToManyField(blank=True, to='catalog.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='tags',
            field=models.ManyToManyField(blank=True, to='catalog.Tag'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, to='catalog.Tag'),
        ),
    ]
