# Generated by Django 2.0.4 on 2018-04-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Продолжительность (s)'),
        ),
    ]
