# Generated by Django 2.0.4 on 2018-04-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180416_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='listeners',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Слушателей'),
        ),
        migrations.AddField(
            model_name='track',
            name='listeners',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Слушателей'),
        ),
        migrations.AddField(
            model_name='track',
            name='playcount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прослушиваний'),
        ),
        migrations.AlterField(
            model_name='album',
            name='playcount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прослушиваний'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='listeners',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Слушателей'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='playcount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прослушиваний'),
        ),
    ]
